env:
  JAVA_HOME: ${{ github.workspace }}/jdk
  JDK_VERSION: latest
  MX_PATH: ${{ github.workspace }}/mx
  SE_SKIP_DRIVER_IN_PATH: 'true'
jobs:
  build:
    if: github.repository == 'oracle/graal'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout oracle/graal
      uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}/graal
    - continue-on-error: true
      name: Checkout oracle/graaljs
      uses: actions/checkout@v4
      with:
        path: ${{ github.workspace }}/js
        repository: oracle/graaljs
        sparse-checkout: 'graal-js

          '
    - continue-on-error: true
      name: Checkout graalvm/mx
      uses: actions/checkout@v4
      with:
        path: ${{ env.MX_PATH }}
        ref: master
        repository: graalvm/mx.git
    - continue-on-error: true
      name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - continue-on-error: true
      name: Fetch LabsJDK
      run: 'mkdir jdk-dl

        ${MX_PATH}/mx --java-home= fetch-jdk --jdk-id labsjdk-ce-${JDK_VERSION} --to
        jdk-dl --alias ${JAVA_HOME}

        '
    - continue-on-error: true
      run: 'cd ${{ github.workspace }}/graal/vm

        ${MX_PATH}/mx --dy /tools,graal-js build

        cd tests/gh_workflows/CDTInspectorTest

        mvn -q compile

        mvn -q exec:exec -Dtestargs="${{ github.workspace }}/graal/sdk/latest_graalvm_home/bin/js
        scripts/StepTest.js"

        '
name: Weekly CDT Inspector
on:
  repository_dispatch:
    types: trigger-ga___cdt-inspect.yml
