env:
  MICRONAUT_CORE_PATH: ${{ github.workspace }}/micronaut-core
  MICRONAUT_JAVA_VERSION: 21
  NATIVE_IMAGE_EXPERIMENTAL_OPTIONS_ARE_FATAL: 'true'
jobs:
  build-graalvm-and-micronaut:
    if: (github.event_name == 'schedule' && github.repository == 'oracle/graal') ||
      (github.event_name != 'schedule')
    name: Native Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout oracle/graal
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Build GraalVM JDK
      uses: ./.github/actions/build-graalvm
      with:
        java-version: ${{ env.MICRONAUT_JAVA_VERSION }}
    - continue-on-error: true
      name: Run nativeTest in Micronaut launch project
      run: 'curl --fail --silent --location --retry 3 --max-time 10 --output demo.zip
        --request GET ''https://launch.micronaut.io/create/default/com.example.demo?lang=JAVA&build=GRADLE&test=JUNIT&javaVersion=JDK_${{
        env.MICRONAUT_JAVA_VERSION }}''

        unzip demo.zip

        cd demo

        ./gradlew nativeTest

        '
    - continue-on-error: true
      name: Checkout micronaut-projects/micronaut-core
      uses: actions/checkout@v4
      with:
        path: ${{ env.MICRONAUT_CORE_PATH }}
        repository: micronaut-projects/micronaut-core
    - continue-on-error: true
      name: Run nativeTest in micronaut-core
      run: 'cd ${{ env.MICRONAUT_CORE_PATH }}

        ./gradlew nativeTest

        '
name: Nightly Micronaut Tests
on:
  repository_dispatch:
    types: trigger-ga___micronaut.yml
permissions:
  contents: read
