env:
  SPRING_JAVA_VERSION: 21
  SPRING_PETCLINIC_PATH: ${{ github.workspace }}/spring-petclinic
jobs:
  build-graalvm-and-spring:
    if: (github.event_name == 'schedule' && github.repository == 'oracle/graal') ||
      (github.event_name != 'schedule')
    name: Native Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout oracle/graal
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Build GraalVM JDK
      uses: ./.github/actions/build-graalvm
      with:
        java-version: ${{ env.SPRING_JAVA_VERSION }}
    - continue-on-error: true
      name: Checkout spring-projects/spring-petclinic
      uses: actions/checkout@v4
      with:
        path: ${{ env.SPRING_PETCLINIC_PATH }}
        repository: spring-projects/spring-petclinic
    - continue-on-error: true
      name: Run nativeTest in spring-petclinic
      run: 'cd ${{ env.SPRING_PETCLINIC_PATH }}

        ./gradlew nativeTest

        '
name: Nightly Spring Tests
on:
  repository_dispatch:
    types: trigger-ga___spring.yml
permissions:
  contents: read
